name: flutter_chat_bloc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_login: ^4.0.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  hydrated_bloc: ^9.0.0-dev.2
  path_provider: ^2.0.11
  intl: ^0.17.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  search_page: ^2.0.0+1
  dash_chat_2: ^0.0.14
  dio: ^4.0.6
  equatable: ^2.0.5
  laravel_echo:
    git:
      url: https://github.com/kakajansh/echo.git
      ref: master
  pusher_client:
    git:
      url: https://github.com/DumbDev168/pusher_client.git
      ref: master
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chat.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
